# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Embed an -M- protocol document as bytes the panel parses at runtime.
#
#     py tools/mkprotocol.py E:/IndustryGrow/store/E0002-000001-M-bringup-protocol.md \
#                            app/protocol_doc.c
#
# The panel does not author procedures (ADR-0030 d8), so it must execute the
# document as carried. Until the removable-media courier exists (F7, blocked on
# O-78) the courier is the build: the same bytes, parsed by the same parser.
# Nothing here interprets the procedure -- this only moves it.
#
# The one transformation is transliteration of non-ASCII punctuation, because
# the panel's font has no glyphs for it. That changes how a step is rendered,
# never which steps there are, their order, or their pass criteria.

import sys
import os

SUBS = {
    "\u2014": "-", "\u2013": "-", "\u2212": "-",
    "\u2018": "'", "\u2019": "'", "\u201c": '"', "\u201d": '"',
    "\u00d7": "x", "\u00b0": " deg", "\u03a9": " ohm", "\u00b5": "u",
    "\u2264": "<=", "\u2265": ">=", "\u2192": "->", "\u2248": "~",
    "\u00b2": "2", "\u00b3": "3", "\u00a0": " ", "\u2011": "-",
    "\u2026": "...", "\u00ad": "",
    # Seen in the store's protocols: section marks and the subscript in CO2.
    "\u00a7": "section ", "\u2082": "2", "\u2081": "1", "\u2083": "3",
    "\u00b1": "+/-", "\u00bd": "1/2", "\u2033": '"', "\u2032": "'",
}


def transliterate(text):
    for bad, good in SUBS.items():
        text = text.replace(bad, good)
    return "".join(c if ord(c) < 128 else "?" for c in text)


def main():
    if len(sys.argv) != 3:
        print("usage: mkprotocol.py <protocol.md> <out.c>")
        return 1

    src, dst = sys.argv[1], sys.argv[2]
    with open(src, "r", encoding="utf-8") as f:
        text = transliterate(f.read())

    data = text.encode("ascii")
    name = os.path.basename(src)
    if name.endswith(".md"):
        name = name[:-3]

    lines = []
    # The header this writes into the generated file. Escaped from REUSE's own
    # scan: the string ends in "\n") and the tool reads that as part of the
    # licence expression, so the whole file fails to parse as valid SPDX.
    # REUSE-IgnoreStart
    lines.append("/* SPDX-License-Identifier: AGPL-3.0-or-later\n")
    # REUSE-IgnoreEnd
    lines.append(" *\n")
    lines.append(" * GENERATED by tools/mkprotocol.py -- do not edit.\n")
    lines.append(" * Source: %s\n" % name)
    lines.append(" *\n")
    lines.append(" * The carried procedure, verbatim but for non-ASCII punctuation. The panel\n")
    lines.append(" * parses this at runtime exactly as it would parse one arriving on media.\n")
    lines.append(" */\n")
    lines.append('#include "protocol.h"\n\n')
    lines.append("const char protocol_doc_name[] = \"%s\";\n\n" % name)
    lines.append("const unsigned char protocol_doc[] = {\n")

    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        lines.append("    " + " ".join("0x%02x," % b for b in chunk) + "\n")

    lines.append("};\n\n")
    lines.append("const unsigned int protocol_doc_len = %u;\n" % len(data))

    with open(dst, "w", encoding="ascii", newline="\n") as f:
        f.writelines(lines)

    print("%s -> %s (%u bytes)" % (name, dst, len(data)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
