/*
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * What the panel knows how to read off the bus.
 *
 * The vocabulary is NOT redefined here: the DSDL in the IndustryGrow repo
 * (firmware/dsdl + firmware/third_party/public_regulated_data_types) is
 * generated by Nunavut at build time and these decoders call the generated
 * deserializers. The subject-ID -> type binding mirrors
 * gateway/files/app/igrow_subjects.py, which is the readable copy of what the
 * node firmware compiles in.
 *
 * Values are converted to display units at decode time (kelvin -> degC,
 * ratio -> %, mole fraction -> ppm), because everything downstream of here is
 * for a human to look at. `unit` names the converted unit, not the SI one.
 */
#ifndef IGROW_SUBJECTS_H
#define IGROW_SUBJECTS_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#define IGROW_SPECTRUM_BANDS 12U

typedef enum {
    IGROW_SIG_SCALAR = 0, /* one plottable number */
    IGROW_SIG_STATE,      /* a boolean condition, carried as 0.0 / 1.0 */
    IGROW_SIG_SPECTRUM,   /* 12 band counts + clear */
    IGROW_SIG_SWEEP,      /* R(T) sweep, up to 10 points */
} igrow_sig_kind_t;

typedef struct {
    bool     have_value;
    float    value;                 /* in the subject's display unit */
    bool     valid;                 /* the payload's own validity flag; true when the type has none */
    uint64_t timestamp_usec;        /* 0 = the publisher had no network time */
    char     text[24];              /* rendered for a tile, e.g. "21.35" or "OPEN" */

    /* IGROW_SIG_SPECTRUM */
    uint16_t band[IGROW_SPECTRUM_BANDS];
    uint16_t clear;
    bool     saturation;

    /* IGROW_SIG_SWEEP */
    uint8_t  n_points;
    float    sweep_ohm[10];
    uint16_t sweep_celsius[10];
} igrow_reading_t;

typedef bool (*igrow_decode_fn)(const uint8_t *payload, size_t size, igrow_reading_t *out);

typedef struct {
    uint16_t         subject_id;
    const char      *name;
    const char      *unit;
    igrow_sig_kind_t kind;
    igrow_decode_fn  decode;
} igrow_subject_t;

/* The whole table, and its length. Ordered by subject-ID. */
extern const igrow_subject_t IGROW_SUBJECTS[];
extern const size_t          IGROW_SUBJECT_COUNT;

/* NULL when the subject-ID is not one the panel knows. */
const igrow_subject_t *igrow_subject_by_id(uint16_t subject_id);

/* Module class a subject belongs to, for grouping in the UI. */
const char *igrow_subject_module(uint16_t subject_id);

#endif /* IGROW_SUBJECTS_H */
