/*
 * SPDX-FileCopyrightText: 2026 The IndustryGrow contributors
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

#include "verify.h"

#include "image.h"
#include "sha256.h"
#include "verify_key.h" /* generated by CMake from IGROW_VERIFY_KEY_HEX */

#include "uECC.h"

#include <string.h>

image_verify_t image_verify_slot(igrow_slot_t slot)
{
    if (!IGROW_VERIFY_KEY_PRESENT) {
        return IMAGE_VERIFY_NO_KEY;
    }
    /* The hash is ours rather than a vendored one, so it says so first. A
     * wrong hash and a wrong signature are indistinguishable from the outside
     * -- both reject every image -- and only this tells them apart. */
    if (!sha256_selftest()) {
        return IMAGE_VERIFY_SELFTEST;
    }

    const igrow_image_header_t *h = image_header(slot);
    if ((h->magic != IGROW_IMAGE_MAGIC) ||
        (h->header_version != IGROW_IMAGE_HEADER_VERSION) ||
        (h->hardware_class != IGROW_HW_CLASS_E0001) ||
        (h->image_length == 0u) ||
        (h->image_length > IGROW_IMAGE_MAX_BODY)) {
        return IMAGE_VERIFY_BAD_HEADER;
    }

    /* The digest binds the body to the header; the signature then covers the
     * header, digest included. That is why the signature does not have to be
     * computed over the whole image and why it cannot sign itself. */
    uint8_t digest[SHA256_DIGEST_LEN];
    sha256((const void *)image_body_addr(slot), h->image_length, digest);
    if (memcmp(digest, h->digest, sizeof(digest)) != 0) {
        return IMAGE_VERIFY_BAD_DIGEST;
    }

    uint8_t signed_hash[SHA256_DIGEST_LEN];
    sha256(h, IGROW_IMAGE_SIGNED_LEN, signed_hash);
    if (uECC_verify(igrow_verify_public_key, signed_hash, sizeof(signed_hash),
                    h->signature, uECC_secp256r1()) != 1) {
        return IMAGE_VERIFY_BAD_SIGNATURE;
    }
    return IMAGE_VERIFY_OK;
}

const char *image_verify_str(image_verify_t result)
{
    switch (result) {
    case IMAGE_VERIFY_OK:            return "verified";
    case IMAGE_VERIFY_NO_KEY:        return "no verification key in this build";
    case IMAGE_VERIFY_SELFTEST:      return "SHA-256 self-test failed";
    case IMAGE_VERIFY_BAD_HEADER:    return "bad header";
    case IMAGE_VERIFY_BAD_DIGEST:    return "body does not match its digest";
    case IMAGE_VERIFY_BAD_SIGNATURE: return "signature rejected";
    default:                         return "unknown";
    }
}
