/*
 * SPDX-FileCopyrightText: 2026 The IndustryGrow contributors
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */
#ifndef IGROW_BOOT_VERIFY_H
#define IGROW_BOOT_VERIFY_H

#include "partition.h"

/*
 * Image verification, ADR-0029 d6: an image is checked against an ECDSA P-256
 * signature over SHA-256 before its slot is marked bootable, with the
 * verification public key held in the bootloader (ADR-0004 d14).
 *
 * It lives here and not in common/ because only the bootloader verifies -- one
 * signed component owns flash writing and verification together, which is what
 * makes "a slot is only marked bootable after a good signature" a property of
 * the code rather than of a convention between two components.
 *
 * The key is compiled in from the build (see the bootloader's verify_key.h,
 * generated by CMake). With no key configured, verification FAILS: an
 * unverified image is never marked bootable, so a build that was never given a
 * key can boot and be flashed over SWD but cannot be updated over the bus.
 */

typedef enum {
    IMAGE_VERIFY_OK = 0,
    IMAGE_VERIFY_NO_KEY,       /* the build carries no verification key */
    IMAGE_VERIFY_SELFTEST,     /* the SHA-256 self-test failed */
    IMAGE_VERIFY_BAD_HEADER,   /* magic, version, class or length */
    IMAGE_VERIFY_BAD_DIGEST,   /* the body is not what the header describes */
    IMAGE_VERIFY_BAD_SIGNATURE /* the header is not signed by our key */
} image_verify_t;

/* Verify the image sitting in `slot`. */
image_verify_t image_verify_slot(igrow_slot_t slot);

/* One short phrase per result, for the console and the diagnostic channel. */
const char *image_verify_str(image_verify_t result);

#endif /* IGROW_BOOT_VERIFY_H */
